// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab04.Migrations;

[DbContext(typeof(OrdersContext))]
[Migration("20260914130350_InitialCreate")]
partial class _20260914130350_InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128");

        modelBuilder.Entity("Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsArchived")
                    .HasColumnType("INTEGER");

                b.Property<string>("Reference")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "Order.ShippingAddress#Address", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("City")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.Property<string>("Country")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.Property<string>("Line1")
                            .IsRequired()
                            .HasColumnType("TEXT");
                    });

                b.HasKey("Id");

                b.HasIndex("ShippingAddress.City")
                    .HasDatabaseName("IX_Orders_ShippingCity");

                b.HasIndex("Reference")
                    .IsUnique();

                b.ToTable("Orders");
            });
#pragma warning restore 612, 618
    }
}
