<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Lab06</RootNamespace>
    <AssemblyName>Lab06</AssemblyName>
    <WarningsAsErrors>CS8509</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Step4_AddACase.cs.txt" />
    <Compile Remove="Step5_NonTransitiveWarning.cs.txt" />
  </ItemGroup>

</Project>
